name: grocery_mart
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
